- name: create cluster.txt
  file: 
    path: "/home/ubuntu/cluster.txt"
    state: touch

- name: Start the cluster
  shell: kubeadm init --ignore-preflight-errors=all --pod-network-cidr=10.244.0.0/16 >> cluster.txt

- name: create .kube directory
  command: mkdir -p /home/ubuntu/.kube

- name: copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/ubuntu/.kube/config
    remote_src: yes
    owner: ubuntu

- name: install Pod network
  become: yes
  become_user: ubuntu
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/a70459be0084506e4ec919aa1c114638878db11b/Documentation/kube-flannel.yml >> pod_setup.txt
  args:
    chdir: /home/ubuntu/
    creates: pod_setup.txt